# FEATURE ENGINEERING #

- it is a process of transforming raw data into features that make machine learning algorithm works better 
- to improve performance of ML models
- it can improve quality

- ## Categorical Features ##
- groups of data 
- will include binary features  ( 0 and 1) True and False - Bool data type e.g. Survived - Yes No i.e 
    sex, m/f

-**category data type** it is **more opitimized** to store cateogrical data
**ordinal data** - u can set up scale in category /level
- ## Numerical Features ##

- where there are numbers 
- will include integers float and integers
- continuous values
grouping up will not make much sense (unless doing clustering)

Different data types in pandas 
- object
- int
- bool
- category
- datetime

In [2]:
import pandas as pd
import seaborn as sns
import numpy as np

In [3]:
iris = sns.load_dataset('iris')

In [4]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [5]:
titanic = sns.load_dataset('titanic')
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [6]:
penguins = sns.load_dataset('penguins')
penguins.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

### Encoding ###

In [7]:
# 1. Manual way
# label encoding 

# - takes a class, assign new integer value to every new class
# column that you can encode 

penguins['species'].unique()


species_codes = {
    'Adelie' : 0,
    'Chinstrap': 1,
    'Gentoo': 2
}

#attack column               
penguins['species_encoded'] = penguins['species'].map(species_codes) # map 

penguins['species_encoded']

0      0
1      0
2      0
3      0
4      0
      ..
339    2
340    2
341    2
342    2
343    2
Name: species_encoded, Length: 344, dtype: int64

In [8]:
penguins['island'].unique()

array(['Torgersen', 'Biscoe', 'Dream'], dtype=object)

In [9]:
island_codes = {
    'Torgersen':0,
    'Biscoe':1,
    'Dream':2
}

penguins['island_encodes'] = penguins['island'].map(island_codes)
penguins['island_encodes']

0      0
1      0
2      0
3      0
4      0
      ..
339    1
340    1
341    1
342    1
343    1
Name: island_encodes, Length: 344, dtype: int64

In [10]:
# 2. Factorization
# factorize (another way)
# species still contains the species name 

#factorize will take the column and assign numbers to the new groups 
species_factorized = pd.factorize(penguins['species']) 
# print(species_factorized) # ada 2D, 1st result. 2 nama index
# new column                   #
penguins['species_factorized'] = species_factorized[0] 
penguins['species_factorized']

0      0
1      0
2      0
3      0
4      0
      ..
339    2
340    2
341    2
342    2
343    2
Name: species_factorized, Length: 344, dtype: int64

In [11]:
# 3. Category_coded
df = penguins.copy()

df['species_cat_encoded']= df['species'].astype('category') #firstly change type to category

df.info()
df['species_cat_encoded'].cat.codes # cat is a datatype only be used on to category

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   species              344 non-null    object
 1   island               344 non-null    object
 2   bill_length_mm       342 non-null    float64
 3   bill_depth_mm        342 non-null    float64
 4   flipper_length_mm    342 non-null    float64
 5   body_mass_g          342 non-null    float64
 6   sex                  333 non-null    object
 7   species_encoded      344 non-null    int64
 8   island_encodes       344 non-null    int64
 9   species_factorized   344 non-null    int64
 10  species_cat_encoded  344 non-null    category
dtypes: category(1), float64(4), int64(3), object(3)
memory usage: 27.5+ KB

0      0
1      0
2      0
3      0
4      0
      ..
339    2
340    2
341    2
342    2
343    2
Length: 344, dtype: int8

In [12]:
#apply three methods to island column

#manually applying label island
island_codes = {
    'Torgersen':0,
    'Biscoe':1,
    'Dream':2
}

penguins['island_encodes'] = penguins['island'].map(island_codes)
penguins['island_encodes']

#using factorize method
island_factorized = pd.factorize(penguins['island'])
penguins['island_factorized'] = island_factorized[0]
penguins['island_factorized']

#using the category

df['island_cat_encoded'] = df['island'].astype('category')
df['island_cat_encoded'].cat.codes

# using the label encoder method

encoder = LabelEncoder()

df['island_sklearn_le'] = encoder.fit_transform(df['island'])
df

NameError: name 'LabelEncoder' is not defined

Multiple methods:
1. manual - for ordinal

In [ ]:
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,species_encoded,island_encodes,species_factorized,species_cat_encoded,island_cat_encoded
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,0,0,0,Adelie,Torgersen
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,0,0,0,Adelie,Torgersen
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,0,0,0,Adelie,Torgersen
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,0,0,0,Adelie,Torgersen
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,0,0,0,Adelie,Torgersen
...,...,...,...,...,...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN,2,1,2,Gentoo,Biscoe
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female,2,1,2,Gentoo,Biscoe
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male,2,1,2,Gentoo,Biscoe
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female,2,1,2,Gentoo,Biscoe
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male,2,1,2,Gentoo,Biscoe

### Label Encoding using sklearn

In [ ]:
# 4.using sklearn labelencoder method
from sklearn.preprocessing import LabelEncoder

# Create LabelEncoder distance
encoder = LabelEncoder()

df['species_sklearn_le'] = encoder.fit_transform(df['species'])
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,species_encoded,island_encodes,species_factorized,species_cat_encoded,island_cat_encoded,species_sklearn_le
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,0,0,0,Adelie,Torgersen,0
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,0,0,0,Adelie,Torgersen,0
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,0,0,0,Adelie,Torgersen,0
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,0,0,0,Adelie,Torgersen,0
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,0,0,0,Adelie,Torgersen,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN,2,1,2,Gentoo,Biscoe,2
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female,2,1,2,Gentoo,Biscoe,2
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male,2,1,2,Gentoo,Biscoe,2
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female,2,1,2,Gentoo,Biscoe,2
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male,2,1,2,Gentoo,Biscoe,2