***One hot encoding***

In [1]:
import pandas as pd
import seaborn as sns
import numpy as np

In [ ]:
# using pandas - one hot encoder
titanic = sns.load_dataset('titanic')
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [4]:
#get dummies method - categories --> Columns
titanic_onehot=pd.get_dummies(titanic, columns=['sex']) # get dummies automatically ignores any missing values
titanic_onehot

,survived,pclass,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,sex_female,sex_male
0,0,3,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,False,True
1,1,1,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,True,False
2,1,3,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,True,False
3,1,1,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,True,False
4,0,3,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,False,True
887,1,1,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,True,False
888,0,3,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,True,False
889,1,1,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,False,True
890,0,3,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,False,True

In [ ]:
# using sklearn onehot encoder
from sklearn.preprocessing import OneHotEncoder
import numpy as np

pl, pw, sl, sw, species, setosa, virginica, versicolor

Species --> object
drop the column betfore fitting into the model

In [13]:
titanic_onehot=titanic.copy()

#create the onehotencoder  # returns nump array  #
encoder = OneHotEncoder(sparse_output=False,handle_unknown='ignore') 

categorical_cols = ['embark_town','alive']

encoded_values = encoder.fit_transform(titanic_onehot[categorical_cols])

#name of new column that dont exist
new_col = encoder.get_feature_names_out(categorical_cols)
new_col


titanic_onehot[new_col] = encoded_values
titanic_onehot

titanic_onehot.drop(columns=['embark_town'],inplace=True)
titanic_onehot

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,alive,alone,embark_town_Cherbourg,embark_town_Queenstown,embark_town_Southampton,embark_town_nan,alive_0,alive_1
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,0,False,0.0,0.0,1.0,0.0,1.0,0.0
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,1,False,1.0,0.0,0.0,0.0,0.0,1.0
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,1,True,0.0,0.0,1.0,0.0,0.0,1.0
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,1,False,0.0,0.0,1.0,0.0,0.0,1.0
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,0,True,0.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,0,True,0.0,0.0,1.0,0.0,1.0,0.0
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,1,True,0.0,0.0,1.0,0.0,0.0,1.0
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,0,False,0.0,0.0,1.0,0.0,1.0,0.0
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,1,True,1.0,0.0,0.0,0.0,0.0,1.0
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,0,True,0.0,1.0,0.0,0.0,1.0,0.0

In [12]:
# 4.using sklearn labelencoder method
from sklearn.preprocessing import LabelEncoder

# Create LabelEncoder distance
encoder = LabelEncoder()

titanic['alive'] = encoder.fit_transform(titanic['alive'])
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,0,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,1,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,1,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,1,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,0,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,1,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,0,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,1,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,0,True