- works best with yes / no kind of problems
-binomial deals with two classes
- multinomial - deals with multiple classes

we are doing regression, in both class
trying to fit a line through the data

in the case above, data is modelled via a straight line using y = mx + c

data is modelled using a sigmoid function: y = sigmoid(x)

Model Logistic Regression:


loss f(x) for logistic = LOG-LOST

In [19]:
import pandas as pd

import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression 

from sklearn.metrics import mean_absolute_error,r2_score

In [2]:
tipsdf = sns.load_dataset('tips')
tipsdf.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

** Feature Engineering** is legit

- The classifier, logistic regression will not accept continuous values.
- we supply categoricla values

In [42]:
smoker_factorized = pd.factorize(tipsdf['smoker'])
tipsdf['smoker_factorized'] = smoker_factorized[0]

sex_factorized = pd.factorize(tipsdf['sex'])
tipsdf['sex_factorized'] = sex_factorized[0]

tipsdf

,total_bill,tip,sex,smoker,day,time,size,smoker_factorized,sex_factorized
0,16.99,1.01,Female,No,Sun,Dinner,2,0,0
1,10.34,1.66,Male,No,Sun,Dinner,3,0,1
2,21.01,3.50,Male,No,Sun,Dinner,3,0,1
3,23.68,3.31,Male,No,Sun,Dinner,2,0,1
4,24.59,3.61,Female,No,Sun,Dinner,4,0,0
...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,0,1
240,27.18,2.00,Female,Yes,Sat,Dinner,2,1,0
241,22.67,2.00,Male,Yes,Sat,Dinner,2,1,1
242,17.82,1.75,Male,No,Sat,Dinner,2,0,1
243,18.78,3.00,Female,No,Thur,Dinner,2,0,0

In [ ]:
# X = tipsdf['total_bill']

# i want to use a single feature
# that feature should be encoded - lets use smoker - no and yes
X = tipsdf[['total_bill']] # 
y = tipsdf['sex_factorized']

In [46]:
model_Logistic = LogisticRegression()
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 0.2, random_state = 42)

model_Logistic.fit(X_train,y_train)

y_pred = model_Logistic.predict(X_test)
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1])

In [51]:
model_Logistic.predict([[i] for i in range(50)])

c:\Users\user\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1])

In [ ]:
r2 = r2_score(y_test, y_pred)  

mae = mean_absolute_error(y_test,y_pred)
mae 

print(f'r2 = {r2}\nmae = {mae}')